// Short effect descriptions for the move bar. `{d}` is replaced by the damage at the creature's
// current evolution stage (base power × stage multiplier, before type effectiveness).

import type { Lang, MoveId } from './sim/types';

export const MOVE_DESC: Record<MoveId, Record<Lang, string>> = {
  shell_ram: { en: 'Instant roll, always hits · {d} dmg', it: 'Rotolata istantanea, va sempre a segno · {d} danni' },
  cinder_spit: { en: 'Fireball projectile · {d} dmg', it: 'Palla di fuoco · {d} danni' },
  heat_shell: { en: 'Takes half damage for 4 s', it: 'Dimezza i danni subiti per 4 s' },
  magma_burst: { en: 'Eruption under the foe · {d} dmg · long charge', it: 'Eruzione sotto il nemico · {d} danni · carica lunga' },
  bubble_bump: { en: 'Instant bounce, always hits · {d} dmg', it: 'Rimbalzo istantaneo, va sempre a segno · {d} danni' },
  water_jet: { en: 'Fast water beam · {d} dmg', it: "Raggio d'acqua veloce · {d} danni" },
  healing_rain: { en: 'Heals 18 HP over 3 s', it: 'Cura 18 PS in 3 s' },
  tidal_crash: { en: 'Huge wave · {d} dmg · long charge', it: 'Onda enorme · {d} danni · carica lunga' },
  horn_charge: { en: 'Instant headbutt, always hits · {d} dmg', it: 'Cornata istantanea, va sempre a segno · {d} danni' },
  leaf_volley: { en: 'Spread of razor leaves · {d} dmg', it: 'Raffica di foglie taglienti · {d} danni' },
  vine_snare: { en: "Roots the foe 2 s: can't dodge", it: 'Blocca il nemico 2 s: non può schivare' },
  thorn_quake: { en: 'Spikes burst from the ground · {d} dmg · long charge', it: 'Spine dal terreno · {d} danni · carica lunga' },
  wing_flick: { en: 'Instant wing strike, always hits · {d} dmg', it: "Colpo d'ala istantaneo, va sempre a segno · {d} danni" },
  spark_dart: { en: 'Very fast spark · {d} dmg', it: 'Scintilla velocissima · {d} danni' },
  static_field: { en: "Halves the foe's stamina regen 5 s", it: "Dimezza la ricarica d'energia nemica per 5 s" },
  thunder_lance: { en: 'Lightning bolt, near instant · {d} dmg · long charge', it: 'Fulmine quasi istantaneo · {d} danni · carica lunga' },
  molten_leap: { en: 'Leaps and slams down · {d} dmg', it: 'Balza e schiaccia il nemico · {d} danni' },
  tide_mirror: { en: 'Reflects the next hit back (1.5 s)', it: 'Riflette il prossimo colpo (1,5 s)' },
  bramble_stampede: { en: "Charge that can't be interrupted · {d} dmg", it: 'Carica inarrestabile · {d} danni' },
  chain_storm: { en: '3 bolts of {d} dmg, each dodgeable', it: '3 fulmini da {d} danni, schivabili' },
  volcanic_ruin: { en: 'Triple eruption · {d} dmg · very long charge', it: 'Tripla eruzione · {d} danni · carica lunghissima' },
  maelstrom: { en: 'Whirlpool · {d} dmg + roots 1.5 s', it: 'Vortice · {d} danni + blocca 1,5 s' },
  ancient_bloom: { en: 'Heals 35 HP over 3 s', it: 'Cura 35 PS in 3 s' },
  rock_hurl: { en: 'Hurls a boulder · {d} dmg', it: 'Scaglia un masso · {d} danni' },
  frost_fin: { en: 'Freezing water beam · {d} dmg', it: 'Raggio gelido · {d} danni' },
  toxic_thorns: { en: 'Poisoned thorns · {d} dmg', it: 'Spine avvelenate · {d} danni' },
  gale_slash: { en: 'Fast cutting wind · {d} dmg', it: 'Vento tagliente veloce · {d} danni' },
  tremor_crush: { en: 'Ground crushes the foe · {d} dmg · very long charge', it: 'Il terreno schiaccia il nemico · {d} danni · carica lunghissima' },
  void_bite: { en: 'Dark bite · {d} dmg · long charge', it: 'Morso oscuro · {d} danni · carica lunga' },
  mind_bloom: { en: 'Psychic blast · {d} dmg · very long charge', it: 'Onda psichica · {d} danni · carica lunghissima' },
  razor_pinion: { en: 'Steel feather bolt · {d} dmg · very long charge', it: "Piuma d'acciaio velocissima · {d} danni · carica lunghissima" },
  pebble_bump: { en: 'Instant bump, always hits · {d} dmg', it: 'Botta istantanea, va sempre a segno · {d} danni' },
  gravel_shot: { en: 'Spray of gravel · {d} dmg', it: 'Raffica di ghiaia · {d} danni' },
  stone_skin: { en: 'Takes half damage for 4 s', it: 'Dimezza i danni subiti per 4 s' },
  fault_quake: { en: 'The ground splits under the foe · {d} dmg · long charge', it: 'Il terreno si spacca sotto il nemico · {d} danni · carica lunga' },
  magma_chunk: { en: 'Flaming boulder · {d} dmg', it: 'Masso infuocato · {d} danni' },
  glacier_drop: { en: 'Ice falls on the foe · {d} dmg · very long charge', it: 'Il ghiaccio cade sul nemico · {d} danni · carica lunghissima' },
  beak_peck: { en: 'Instant peck, always hits · {d} dmg', it: 'Beccata istantanea, va sempre a segno · {d} danni' },
  feather_dart: { en: 'Fast feather · {d} dmg', it: 'Piuma veloce · {d} danni' },
  dizzy_gale: { en: "Halves the foe's stamina regen 5 s", it: "Dimezza la ricarica d'energia nemica per 5 s" },
  hurricane: { en: 'Huge whirlwind · {d} dmg · long charge', it: 'Enorme turbine · {d} danni · carica lunga' },
  shadow_talon: { en: 'Dark claw strike · {d} dmg', it: 'Artiglio oscuro · {d} danni' },
  draco_zephyr: { en: 'Dragon wind beam · {d} dmg · very long charge', it: 'Soffio di drago · {d} danni · carica lunghissima' },
  paw_tap: { en: 'Instant paw, always hits · {d} dmg', it: 'Zampata istantanea, va sempre a segno · {d} danni' },
  psy_orb: { en: 'Slow psychic orb · {d} dmg', it: 'Sfera psichica lenta · {d} danni' },
  calm_mind: { en: 'Heals 18 HP over 3 s', it: 'Cura 18 PS in 3 s' },
  mind_crush: { en: 'Psychic beam · {d} dmg · long charge', it: 'Raggio psichico · {d} danni · carica lunga' },
  spirit_hex: { en: 'Haunting curse · {d} dmg', it: 'Maledizione spettrale · {d} danni' },
  astral_blade: { en: 'Blade of starlight · {d} dmg · very long charge', it: 'Lama di luce stellare · {d} danni · carica lunghissima' },
  shade_nip: { en: 'Instant nip, always hits · {d} dmg', it: 'Pizzico istantaneo, va sempre a segno · {d} danni' },
  spook_bolt: { en: 'Fast ghostly bolt · {d} dmg', it: 'Dardo spettrale veloce · {d} danni' },
  dread_stare: { en: "Roots the foe 2 s: can't dodge", it: 'Blocca il nemico 2 s: non può schivare' },
  nightmare_wave: { en: 'Wave of darkness · {d} dmg · long charge', it: 'Onda di oscurità · {d} danni · carica lunga' },
  wisp_flame: { en: 'Ghost fire · {d} dmg', it: 'Fuoco fatuo · {d} danni' },
  grave_miasma: { en: 'Poison fog from the grave · {d} dmg · very long charge', it: 'Nebbia velenosa · {d} danni · carica lunghissima' },
  claw_swipe: { en: 'Instant swipe, always hits · {d} dmg', it: 'Graffio istantaneo, va sempre a segno · {d} danni' },
  wyrm_spit: { en: 'Dragon fire ball · {d} dmg', it: 'Palla di fuoco di drago · {d} danni' },
  scale_guard: { en: 'Takes half damage for 4 s', it: 'Dimezza i danni subiti per 4 s' },
  meteor_fall: { en: 'Meteor from the sky · {d} dmg · long charge', it: 'Meteora dal cielo · {d} danni · carica lunga' },
  storm_fang: { en: 'Crackling bite · {d} dmg', it: 'Morso scoppiettante · {d} danni' },
  inferno_roar: { en: 'Roaring fire beam · {d} dmg · very long charge', it: 'Raggio di fuoco · {d} danni · carica lunghissima' },
  goo_slap: { en: 'Instant slap, always hits · {d} dmg', it: 'Schiaffo istantaneo, va sempre a segno · {d} danni' },
  acid_spit: { en: 'Acid glob · {d} dmg', it: 'Sputo di acido · {d} danni' },
  sticky_goo: { en: "Roots the foe 2 s: can't dodge", it: 'Blocca il nemico 2 s: non può schivare' },
  sludge_wave: { en: 'Wave of toxic sludge · {d} dmg · long charge', it: 'Onda di fango tossico · {d} danni · carica lunga' },
  swamp_jet: { en: 'Muddy water beam · {d} dmg', it: "Getto d'acqua torbida · {d} danni" },
  mire_slam: { en: 'Slams the ground · {d} dmg · very long charge', it: 'Schiaccia il terreno · {d} danni · carica lunghissima' },
  cog_bash: { en: 'Instant bash, always hits · {d} dmg', it: 'Botta istantanea, va sempre a segno · {d} danni' },
  nail_shot: { en: 'Fast steel nails · {d} dmg', it: 'Chiodi di acciaio veloci · {d} danni' },
  self_repair: { en: 'Heals 18 HP over 3 s', it: 'Cura 18 PS in 3 s' },
  iron_crush: { en: 'Iron slam · {d} dmg · long charge', it: 'Schianto di ferro · {d} danni · carica lunga' },
  arc_weld: { en: 'Sparking weld · {d} dmg', it: 'Saldatura elettrica · {d} danni' },
  forge_blast: { en: 'Furnace beam · {d} dmg · very long charge', it: 'Raggio di fornace · {d} danni · carica lunghissima' },
  snow_bump: { en: 'Instant bump, always hits · {d} dmg', it: 'Spinta istantanea, va sempre a segno · {d} danni' },
  ice_shard: { en: 'Fast ice shard · {d} dmg', it: 'Scheggia di ghiaccio veloce · {d} danni' },
  frost_bind: { en: "Roots the foe 2 s: can't dodge", it: 'Blocca il nemico 2 s: non può schivare' },
  blizzard: { en: 'Wave of snow · {d} dmg · long charge', it: 'Onda di neve · {d} danni · carica lunga' },
  aurora_gaze: { en: 'Aurora ray · {d} dmg', it: 'Raggio aurorale · {d} danni' },
  avalanche: { en: 'Crashing avalanche · {d} dmg · very long charge', it: 'Valanga rovinosa · {d} danni · carica lunghissima' },
  sky_judgement: { en: 'Lightning from the sky · {d} dmg · very long charge', it: 'Fulmine dal cielo · {d} danni · carica lunghissima' },
};
